"""empty message

Revision ID: 27e71be9d284
Revises: e7f3007b2ba8
Create Date: 2026-03-25 16:44:30.355318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e71be9d284'
down_revision = 'e7f3007b2ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=False))
        batch_op.drop_column('last_name_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
